name: Behavior Change
favicon: null
layout_spectrum: 1
typography_spectrum: 0.7497511128894985
title: behavior change
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#477129'
    - '#bbbbbb'
    - '#010101'
    - '#ffffff'
    - '#7b1d2b'
  brandStrength: 1
  lightness: 0.5625
  saturation: 0
  rhythmicContrast: 1
purpose: []
