name: Behavior Change
favicon: null
layout_spectrum: 0.54715
typography_spectrum: 0.7497511128894985
title: behavior change
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#010101'
    - '#b08b79'
    - '#e6cabc'
    - '#816b00'
  brandStrength: 0.625
  lightness: 0.5625
  saturation: 0
  rhythmicContrast: 1
purpose: []
